Github Actions

diff --git a/.github/workflows/model_testing.yml b/.github/workflows/model_testing.yml
--- a/.github/workflows/model_testing.yml
+++ b/.github/workflows/model_testing.yml
@@ -37,15 +37,15 @@ jobs:
             if [ -d "scholarly" ]; then
               cd scholarly
               git pull origin main
-              python -m venv venv
+              python3 -m venv venv
               source venv/bin/activate
               pip install -r requirements.txt
-              python manage.py test || { echo "Tests failed"; cd ..; rm -rf scholarly; exit 1; }
+              python3 -m manage test || { echo "Tests failed"; cd ..; rm -rf scholarly; exit 1; }
             else
               git clone https://github.com/mojalefakodisang/scholarly
               cd scholarly
-              python -m venv venv
+              python3 -m venv venv
               source venv/bin/activate
               pip install -r requirements.txt
-              python manage.py test || { echo "Tests failed"; cd ..; rm -rf scholarly; exit 1; }
+              python3 -m manage test || { echo "Tests failed"; cd ..; rm -rf scholarly; exit 1; }
             fi
